import { Router } from "express";
import user from "./user/users";
import role from "./user/roles";
import permissions from "./user/permissions";
import asignPermission from "./user/asignPermissions";
import product from "../routes/products/products.routes";
const router = Router();
// router.use("/", oauth);
router.use("/", user);
router.use("/", role);
router.use("/", permissions);
router.use("/", asignPermission);
router.use("/", product);
export default router;
