import { Router, Request, Response } from "express";
import { createUser, verifyEmailOtp } from "../controllers/user.controller";
import { alreadyExistOrNotEmailforRegister } from "../middlewares/emailAlreadyExist.auth";
import { sentOtpByMail } from "../services/sentOtpViaMail";
import { upload, } from "../middlewares/multer.middleware";
const user = Router();
user.post("/registerEmail", alreadyExistOrNotEmailforRegister, sentOtpByMail);
user.post("/verifyEmailOtp", verifyEmailOtp);
user.post("/createUserWithDetais",upload.single("profilePic"), createUser);
export default user;
